blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/WrichikBasu/Mahalaya-Android/discussions/categories/q-a
    about: Ask and answer questions here.
  - name: Ideas/Feature requests
    url: https://github.com/WrichikBasu/Mahalaya-Android/discussions/categories/ideas-feature-requests
    about: Propose a new feature for this app.
